my:
  mood:
    today: 周五
    content: 期待周末
    author: "小程序员"

  feature:
      helloSwitch: false
      closeMsg: "该接口正在维护，10分钟后再来吧"


sy:
  sms:
    ccp:
      serverIp: app.cloopen.com
      port: 8883
      accountSId: 2c94811c9860a9c4019917b9272c1dc7
      accountToken: 2eb03e2a7ee7418db43fd895dd5eec6d
      appId: 2c94811c9860a9c4019917b928871dce
      templateId: 1




